[package]
name = "futures-buffered"
version = "0.2.0"
edition = "2021"
description = "future concurrency primitives with emphasis on performance and low memory usage"
license = "MIT"
repository = "https://github.com/conradludgate/futures-buffered"
authors = ["Conrad Ludgate <conradludgate@gmail.com"]
categories = ["asynchronous"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures-core = "0.3.21"
futures-util = "0.3.21"
pin-project-lite = "0.2"

[dev-dependencies]
criterion = { version = "0.4" }
futures = "0.3.21"
hyper = { version = "0.14", features = ["client", "http2", "tcp"] }
tokio = { version = "1", features = ["full", "macros"] }

[[bench]]
name = "batch"
harness = false
