[package]
name = "futures-buffered"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures-util = "0.3.21"
pin-project-lite = "0.2"

[dev-dependencies]
criterion = { version = "0.4" }
futures = "0.3.21"
hyper = { version = "0.14", features = ["client", "http2", "tcp"] }
tokio = { version = "1", features = ["full", "macros"] }

[[bench]]
name = "batch"
harness = false
