name: Rust

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  miri:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: miri
          override: true

      - name: Run cargo miri test
        run: cargo miri test --tests

  clippy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install latest rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: beta
          override: true
          components: clippy

      - name: Run clippy
        run: cargo clippy -- -D warnings

  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install latest rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt

      - name: Format
        run: cargo fmt -- --check
